# Generated by Django 5.0.6 on 2024-06-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="body",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
