# Generated by Django 5.0.6 on 2024-06-25 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_remove_posts_user_posts_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="post_count",
            new_name="like_count",
        ),
        migrations.RenameField(
            model_name="posts",
            old_name="post_like",
            new_name="liked_by",
        ),
    ]
