# Generated by Django 5.0.6 on 2024-06-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="posts",
            options={"verbose_name_plural": "Posts"},
        ),
        migrations.AlterField(
            model_name="comments",
            name="body",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
