# Generated by Django 5.0.6 on 2024-06-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_alter_comments_options_alter_posts_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="body",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
