# Generated by Django 5.0.6 on 2024-06-26 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_alter_comments_body"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="posts",
        ),
        migrations.AddField(
            model_name="comments",
            name="posts",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_comment",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
