# Generated by Django 5.0.6 on 2024-06-26 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_remove_comments_posts_comments_posts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="posts",
            new_name="post",
        ),
    ]
