# Generated by Django 5.0.6 on 2024-06-19 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="follow",
            field=models.ManyToManyField(
                blank=True, related_name="follow", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="follow_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
