# Generated by Django 5.0.6 on 2024-05-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1000)),
                ("location", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
                ("contact", models.CharField(max_length=12)),
                ("event_date", models.DateTimeField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("more_information", models.CharField(max_length=255)),
            ],
        ),
    ]
