# Generated by Django 5.0.6 on 2024-05-31 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catogory", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="event_category",
            field=models.OneToOneField(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="events.eventcategories",
            ),
            preserve_default=False,
        ),
    ]
