# Generated by Django 5.0.6 on 2024-05-31 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_eventcategories_eventmodel_event_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventcategories",
            old_name="catogory",
            new_name="category",
        ),
    ]
