# Generated by Django 5.0.6 on 2024-06-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_eventmodel_event_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmodel",
            name="no_of_likes",
            field=models.IntegerField(default=0),
        ),
    ]
