# Generated by Django 5.0.6 on 2024-06-11 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_eventmodel_no_of_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventmodel",
            name="no_of_likes",
        ),
    ]
