# Generated by Django 5.0.6 on 2024-06-12 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_eventmodel_likes_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmodel",
            name="like_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="eventmodel",
            name="likes",
        ),
        migrations.DeleteModel(
            name="Likes",
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
