# Generated by Django 5.0.6 on 2024-06-13 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "events",
            "0009_remove_eventmodel_like_count_remove_eventmodel_likes_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmodel",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="event_fav", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
