# Generated by Django 5.0.6 on 2024-06-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_eventmodel_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmodel",
            name="favorites_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="liked_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
